name: Sync Moodle with Server

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22 44.211.228.79 >> ~/.ssh/known_hosts

      - name: Sync server with GitHub
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@44.211.228.79 << 'EOF'
            cd /var/www/html/moodle
            git config user.name "CI/CD Bot"
            git config user.email "qamaralmousa47@gmail.com"
            git add .
            if ! git diff-index --quiet HEAD; then
              git commit -m "Auto-sync server files"
              git push origin dev
            fi
            git fetch origin  main
            git reset --hard origin/main
          EOF
